#!/bin/bash
GREEN="\e[92m"
printf "${GREEN}"
echo "                                                  "
echo " ____   ___  __  __    _    ___ _   _             "
echo "|  _ \ / _ \|  \/  |  / \  |_ _| \ | |            "
echo "| | | | | | | |\/| | / _ \  | ||  \| |            "
echo "| |_| | |_| | |  | |/ ___ \ | || |\  |            "
echo "|____/ \___/|_|  |_/_/   \_\___|_| \_|            "
echo "                                                  "
echo  "____  _____ ____   ___  _ __     _______ ____    "
echo "|  _ \| ____/ ___| / _ \| |\ \   / / ____|  _ \   "
echo "| |_) |  _| \___ \| | | | | \ \ / /|  _| | |_) |  "
echo "|  _ <| |___ ___) | |_| | |__\ V / | |___|  _ <   "
echo "|_| \_\_____|____/ \___/|_____\_/  |_____|_| \_\  "
echo "                                                  "

echo " Find me on twitter @imhaxormad "
printf "${GREEN}"
printf "===========================================================================================\n"
echo "Tool to test if the subdomains/domains from the lists resolves and create a file resolves"
printf "${GREEN}"
printf "===========================================================================================\n"
echo -e "\e[38;5;82m Please type in the filename with the domains lists to check if it resolves"
read output
printf "${GREEN}"
printf "============================================================================================\n"
echo -e "\e[38;5;198m Enter Destination File Name:"
read outputs
printf "${GREEN}"
printf "=======================================================\n"
while read domain; do if host "$domain" > /dev/null; then echo $domain; fi; done < $output >> $outputs
printf "=======================================================\n"
echo -e "\e[38;5;82m All resolving domains name has been added to $outputs file. "
printf "${GREEN}"
printf "Thank You for Using the Tool!"
echo "                       "